### ISSUE TITLE
how to set the time zone in the api request ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#11]
I mean  "scheduled_date"  in the below. 

data = { "name":"Campaign sent via the API",
        "subject":"My subject",   
        "from_name":"From name",
        "from_email":"libertytrustgroupllc@gmail.com",
		"html_content":"Congratulations ! You successfully sent this example campaign via the SendinBlue API.",
		"listid": [2],
		"scheduled_date":"2017-01-30 00:00:00"
}

**Comment by amitkumarjha** [comment]
Hi @jpca999 ,

Thank you for contacting us.

You can set the timezone from the front end, You will be not able to set timezone from API.
[Setting Time Zone](https://my.sendinblue.com/advanced/config)

**Comment by PManager1** [comment]
Thanks got it,

How to send email I've few more questions. Where do I ask you ? 


Best Regards,
Jay

**Comment by amitkumarjha** [comment]
Hi @jpca999 ,

Thank you for contacting us.

You can raise support request from the website and put all the queries in the ticket.

https://account.sendinblue.com/support
