### ISSUE TITLE
Give me a way to send the mail  "now" ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#12]
I mean  "scheduled_date"  in the below. 

data = { "name":"Campaign sent via the API",
        "subject":"My subject",   
        "from_name":"From name",
        "from_email":"libertytrustgroupllc@gmail.com",
		"html_content":"Congratulations ! You successfully sent this example campaign via the SendinBlue API.",
		"listid": [2],
		"scheduled_date":"2017-01-30 00:00:00"
}

**Comment by amitkumarjha** [comment]
Hello @jpca999

Thank you for contacting us.
Please use the following parameter in the JSON data:
```
"send_now":1
```
You can get more info on the following link:
[Send Now](https://apidocs.sendinblue.com/campaign/#2)
