### ISSUE TITLE
how do i remove the previously created (mistakenly) campaign ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#13]
![image](https://cloud.githubusercontent.com/assets/1026325/22432540/2ffe3ee0-e6e3-11e6-8212-7fdd29d3ef6a.png)

**Comment by amitkumarjha** [comment]
Hello @jpca999
Thank you for contacting us.
Please check this link.
[Delete a campaign](https://apidocs.sendinblue.com/campaign/#3)
