### ISSUE TITLE
how to send the campaign email to single user in real time i.e not the whole list of users,   while im on phone talking to client, I want to send that email to just one.. 

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#15]
whats the api to send campaing to single user ( email ) ?

**Comment by amitkumarjha** [comment]
Hi @jpca999 ,

Thank you for contacting us.

You can check below two links to send emails to single user.
[Send Emails to single user](https://apidocs.sendinblue.com/campaign/#7)
[Create Campaign to and send now](https://apidocs.sendinblue.com/campaign/#2)
