### ISSUE TITLE
why does it show this error message ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#16]
now i can send the emails ( atleast on scheduled time ) it send me success message, ) why does it show this error message ?

![image](https://cloud.githubusercontent.com/assets/1026325/22433547/bdb6ac38-e6e6-11e6-86c4-8e4d299d7469.png)

**Comment by amitkumarjha** [comment]
Hi @jpca999,
Thank you for contacting us. 
Your account is not validated yet, so you are receiving this error message. Please raise a support request by following  below link.
https://account.sendinblue.com/support
