### ISSUE TITLE
what api should i use if I have to send custom subject for the email ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#18]
lets say i want to send a user the template/ campaign A that is already built in my account, but i want to send him new flashy subject line for this specific person... so how to manipulate the subject line only ?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
