### ISSUE TITLE
Provide library on npm

### ISSUE THREAD

**Issue by elyas-bhy** [mailin-api/mailin-api-node-js#2]
Any plans on providing this library on npm? It would be much easier to install, use and update.
It's as simple as adding a _package.json_ file with the correct metadata, listing `restler` as a dependency, and exporting the `Mailin` object through `module.exports`.

I could submit a pull request if you are willing to have a look at it.

**Comment by fabiusss** [comment]
+1

**Comment by elyas-bhy** [comment]
@fabiusss As a temporary workaround, you can refer to my fork: [elyas-bhy/mailin-api-node-js](https://github.com/elyas-bhy/mailin-api-node-js).
To use my fork as a node.js dependency, simply include the following in your `package.json`:  
`"mailin-api": "git+https://github.com/elyas-bhy/mailin-api-node-js.git#master"`

I've exported only the V2.0 API. Let me know if you need the V1.0 as well.
Note that `author` and `license` fields are temporary placeholders and subject to change when/if Mailin decides to accept pull requests.

**Comment by laurynas-karvelis** [comment]
This node "module" really needs to be packaged to npm registry. Also, the actual interface should be more intuitive enabling developers to use `cb(err, response)` pattern and return promises.

**Comment by kelkes** [comment]
Thats really a showstopper for me. Its done in less then 15minutes.

**Comment by abelsoares** [comment]
👍 for npm and promises

**Comment by otaviosoares** [comment]
+1

**Comment by azachar** [comment]
+1

**Comment by xavxyz** [comment]
👍

**Comment by ekta-slit** [comment]
Hello,

Thank you for your messages.
The library on NPM is available now.
Please refer [here](https://www.npmjs.com/package/sendinblue-api)

Regards,
SendinBlue Team

**Comment by azachar** [comment]
Perfect, thanks!
