### ISSUE TITLE
run javascriopt befoe the email loads , how can we do that ?

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#20]
Hi there, 

I get the same html content from my boss, everytime, i.e the fields change but most of the html settings are same all the time. 

Before i forward that html to m email list, i want to strip away some html like change the names  for some fields, 
change the numbers by a specific percent. 

So in order to achieve this, I want to run javascript / jQuery for that.

Question:  Does the html inside the email runs the jQuery / javascript before it loads the email on the page ?

Or is there another way to get this done ?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
