### ISSUE TITLE
Reply doesn't work

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#22]
Hi there, So when I send an email from Sendinblue it doesn't reply back from the sent email 

Ie no email goes out to libertytrustgroup@gmail.com.54064330.t-sender-sib.com

If I wanna receive Thebes's emails which other people send me by hitting reply - how can I make that happen ?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
