### ISSUE TITLE
Cannot install mailin from npm

### ISSUE THREAD

**Issue by FaisalAhmedAnsari** [mailin-api/mailin-api-node-js#23]
When i am trying to install using npm, I am getting following error.

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}`

I am using windows 7

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
