### ISSUE TITLE
False return 

### ISSUE THREAD

**Issue by yongshenglian** [mailin-api/mailin-api-node-js#24]
Try the example. It seems the status is always "success" even when the api never sends email out.  For example, when the email address is false. From the sendinBlue dashboard, the request is never made even the status="success"

	client.send_email(data).on('complete', function(msg) {
		var obj=JSON.parse(msg);
		console.log(obj);
		
		var status=obj.code;
		if (obj.code='success') {
			console.log('send message successfully');
			
		}
		else console.log('message was not sent');
		
		//return cb();
		
	});

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
