### ISSUE TITLE
Provide Documentation for send_email function

### ISSUE THREAD

**Issue by curtislarson** [mailin-api/mailin-api-node-js#3]
Hello,

I have been attempting to use the SendInBlue Node.js API however there is no JavaScript documentation on the send_email function (the only available documentation I found was in PHP).

I continue to receive a "Bad sender address syntax" despite trying many variations of the "from" field. Could you provide an example of how to format the "from" field when using send_email with Node.js?

Thanks,

Curtis

**Comment by ekta-slit** [comment]
Hello Curtis,

Thank you for contacting us.

Our API documentation is available in 6 different languages, including Node.js.
Please refer [Apidoc](https://apidocs.sendinblue.com/tutorial-sending-transactional-email/) and click on Node.js code preference to check the sample for send_email function.

Regards,
Sendinblue Team
