### ISSUE TITLE
ReferenceError: Mailin is not defined

### ISSUE THREAD

**Issue by SoporteCORASA** [mailin-api/mailin-api-node-js#5]
Am I the only one with this error?

> ReferenceError: Mailin is not defined
>     at sendEmailAndResponde (RegistroPaquete.controller.js:104:24)
>     at create (RegistroPaquete.controller.js:95:11)
>     at Layer.handle [as handle_request](/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/layer.js:95:5)
>     at next (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/route.js:131:13)
>     at Route.dispatch (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request](/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/layer.js:95:5)
>     at /media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:277:22
>     at Function.process_params (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:330:12)
>     at next (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:271:10)
>     at Function.handle (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:176:3)
>     at router (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:46:12)
>     at Layer.handle [as handle_request](/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:312:13)
>     at /media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:280:7
>     at Function.process_params (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:330:12)
>     at next (/media/soporte/SoporteCorasa/DesarrollosCSD/Web/DashboardCSD/node_modules/express/lib/router/index.js:271:10)
> POST /api/RegistroPaquetes?CredencialId=1&DashboardUserId=4&EmailEmpresa=soporte@grupocorasa.mx&cantidad=15&paquete=Paquete+de+15+timbrado&saldo=15&tipo=timbrado 500 1824.557 ms - -

My code is:
`require("../mailin-api-node-js-master/V2.0/mailin.js");
      var client = new Mailin("https://api.sendinblue.com/v2.0", config.sendinBlue.Key, 5000);
      data = {
          "id": 2,
          "to": {
              mails
          },
          "attr": {
              "PAQUETE": req.body.paquete,
              "CANTIDAD": req.body.cantidad,
              "RFC": req.body.rfc,
              "FECHA": req.body.fechaAsignacion
          },
          "from": ["no-reply@corasasoft.com"]
      }
      client.send_transactional_template(data).on('complete', function(data) {
        statusCode = 200;
        console.log(data);
      });`

And its crashing here:

`require("../mailin-api-node-js-master/V2.0/mailin.js");`

**Comment by grotaldo** [comment]
same here

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-nodejs-library
