### ISSUE TITLE
{"code":"failure","message":"Invalid list id passed: 1","data":[]}

### ISSUE THREAD

**Issue by PManager1** [mailin-api/mailin-api-node-js#9]
![image](https://cloud.githubusercontent.com/assets/1026325/22401566/169b4d18-e5a7-11e6-9202-8ec381283490.png)

{"code":"failure","message":"Invalid list id passed: 1","data":[]}

I dont know where am i wrong ?

Isn't the ID = 1 ?
![image](https://cloud.githubusercontent.com/assets/1026325/22401569/338e1496-e5a7-11e6-8d08-349997b7a745.png)

**Comment by ekta-slit** [comment]
Hello @jpca999 

Thank you for contacting us.

The ID 1 you passed is actually the active template ID and not the list ID. Its clear from the screen shot you provided.

You can get all the list details from [get_lists()](https://apidocs.sendinblue.com/list/#1) API ( Front end: https://my.sendinblue.com/lists )


Regards
SendinBlue Team

**Comment by PManager1** [comment]
I get this error for list api :  https://github.com/mailin-api/mailin-api-node-js/issues/10
fyi resolved. 
I appreciate your time in this issue. 
Feel free to login in to my account and see whats going wrong---


How to send the campaign email right now...  not at the scheduled time......


Here's the code, 

var sendinblue = require('sendinblue-api');

require("./mailin.js");

var client = new Mailin("https://api.sendinblue.com/v2.0","aHEC6RXyt4ZQgVLx");

data = { "name":"Campaign sent via the API",
        "subject":"My subject",   
        "from_name":"From name",
        "from_email":"libertytrustgroupllc@gmail.com",
		"html_content":"Congratulations ! You successfully sent this example campaign via the SendinBlue API.",
		"listid": [2],
		"scheduled_date":"2017-01-30 13:00:00"
} 

client.create_campaign(data).on('complete', function(data) {
    console.log(data);
      });
